echo Starting Deletion
rm -rf ../data/ff/original_sequences/youtube/c23/images
echo Deleted Youtube
rm -rf ../data/ff/original_sequences/actors/c23/images
echo Deleted Actors
rm -rf ../data/ff/manipulated_sequences/Deepfakes/c23/images
echo Deleted Deepfakes
rm -rf ../data/ff/manipulated_sequences/Face2Face/c23/images
echo Deleted Face2Face
rm -rf ../data/ff/manipulated_sequences/FaceSwap/c23/images
echo Deleted FaceSwap
rm -rf ../data/ff/manipulated_sequences/NeuralTextures/c23/images
echo Deleted NeuralTextures
rm -rf ../data/ff/manipulated_sequences/FaceShifter/c23/images
echo Deleted FaceShifter